# .github/workflows/keep-alive.yml
name: Keep Service Awake (Test Version)

on:
  schedule:
    # Executa a cada 7 minutos, das 12h às 21h UTC (9h às 18h BRT), de segunda a sexta.
    - cron: '*/7 12-21 * * 1-5'

  workflow_dispatch: # Permite execução manual

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service to keep it awake
        run: |
          echo "Pinging service at ${{ secrets.SERVICE_URL }} to keep it awake..."
          response=$(curl -s -w "%{http_code}" "${{ secrets.SERVICE_URL }}")
          echo "Service responded with: $response"
