name: Trigger Render Redeploy

on:
  schedule:
    # 11:00 BRT (UTC-3) = 14:00 UTC
    - cron: '0 14 * * *'
    # 16:00 BRT (UTC-3) = 19:00 UTC  
    - cron: '0 19 * * *'

  # Mantém a opção de execução manual
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          echo "🚀 Triggering a new deploy on Render..."
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.RENDER_DEPLOY_HOOK_URL }}")
          http_code=${response: -3}
          body=${response::-3}

          echo "Response Body: $body"
          echo "HTTP Status Code: $http_code"
          echo "Executed at: $(date)"

          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "✅ Deploy hook successfully triggered on Render."
          else
            echo "❌ Failed to trigger Render deploy hook."
            exit 1
          fi

      - name: Wait for deployment
        run: |
          echo "⏳ Waiting for deployment to complete..."
          sleep 60

      - name: Wake up service with ping
        run: |
          echo "🏓 Pinging service to ensure it's awake..."
          for i in {1..3}; do
            echo "Attempt $i of 3..."
            response=$(curl -s -w "%{http_code}" -m 30 "${{ secrets.SERVICE_URL }}" || echo "000")
            http_code=${response: -3}
            
            if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 400 ]; then
              echo "✅ Service is awake and responding!"
              exit 0
            fi
            
            echo "Service not ready yet, waiting 15 seconds..."
            sleep 15
          done
          
          echo "⚠️ Service may still be starting up"
