name: Trigger Render Redeploy - Test Mode

on:
  schedule:
    # Executa a cada 5 minutos (intervalo mínimo permitido)
    - cron: '*/5 * * * *'
  
  # Mantém a opção de execução manual
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          echo "🚀 Triggering a new deploy on Render (Test Mode - Every 5min)..."
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.RENDER_DEPLOY_HOOK_URL }}")
          http_code=${response: -3}
          body=${response::-3}

          echo "Response Body: $body"
          echo "HTTP Status Code: $http_code"
          echo "Executed at: $(date)"

          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "✅ Deploy hook successfully triggered on Render."
          else
            echo "❌ Failed to trigger Render deploy hook."
            exit 1
          fi

      # Opcional: ping para garantir que o serviço acorde
      - name: Wake up service
        run: |
          echo "🏓 Pinging service to ensure it's awake..."
          curl -s -m 10 "${{ secrets.SERVICE_URL }}" || echo "Service may still be starting"
